name: simplify
description: "Simplify - Educational Platform"

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  app_links: ^7.0.0
  appinio_video_player: any
  audio_waveforms: ^2.0.2
  audioplayers: ^6.5.1
  awesome_snackbar_content: ^0.1.8
  badges: ^3.1.2
  bloc: ^9.2.0
  cached_network_image: ^3.4.1
  chewie: ^1.13.0
  connectivity_plus: ^7.0.0
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_info_plus: ^12.3.0
  device_preview: ^1.3.1
  dio: ^5.9.1
  dio_cache_interceptor: ^4.0.5
  dtd: ^4.0.0
  easy_date_timeline: ^2.0.9
  equatable: ^2.0.8
  file_picker: ^10.3.10
  firebase_core: ^4.4.0
  firebase_messaging: ^16.1.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^9.1.1
  flutter_inappwebview: ^6.1.5
  flutter_lints: ^6.0.0
  flutter_local_notifications: ^20.1.0
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  get_it: ^9.2.0
  google_fonts: ^8.0.1
  google_sign_in: ^7.2.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  http: ^1.6.0
  hydrated_bloc: ^10.1.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  json_annotation: ^4.10.0
  json_rpc_2: ^4.0.0
  jwt_decoder: ^2.0.1
  lottie: ^3.3.2
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  photo_view: ^0.15.0
  pinput: ^6.0.2
  pretty_dio_logger: ^1.4.0
  record: ^6.2.0
  retrofit: ^4.9.2
  shared_preferences: ^2.5.4
  shimmer: ^3.0.0
  signalr_netcore: ^1.4.4
  skeletonizer: ^2.1.3
  smart_auth: ^3.2.0
  smooth_page_indicator: ^2.0.1
  stack_trace: ^1.12.1
  timeago: ^3.7.1
  timelines_plus: ^1.0.8
  toastification: ^3.0.3
  url_launcher: ^6.3.2
  uuid: ^4.5.2
  video_player: ^2.10.1
  voice_note_kit: ^1.3.3
  wave_blob: ^1.0.5
  web: ^1.1.1
  webview_flutter: ^4.13.1
  webview_flutter_android: ^4.10.11
  webview_flutter_platform_interface: ^2.14.0
  webview_flutter_wkwebview: ^3.23.6

dev_dependencies:
  build_runner: ^2.11.1

  # App Configuration
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.11.1
  icons_launcher: ^3.0.3
  json_serializable: ^6.12.0
  retrofit_generator: ^10.2.3

flutter:
  uses-material-design: true
  assets:
    - assets/audios/
    - assets/fonts/
    - assets/icons/
    - assets/images/
    # - assets/lord/
    - assets/lottie/
    - assets/svgs/

flutter_intl:
  enabled: true